name: "Docker Build and Push"

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

permissions:
  contents: read
  packages: write
  # This is used to complete the identity challenge
  # with sigstore/fulcio.
  id-token: write

jobs:
  build-push:
    uses: darbiadev/.github/.github/workflows/docker-build-push.yaml@307c66955ab6d811fbeb45f8e49dfe5d51e5d285
