name: "Python CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@b0478c2e1835f75bfe679b05a5f72c46c969b938

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@b0478c2e1835f75bfe679b05a5f72c46c969b938

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@b0478c2e1835f75bfe679b05a5f72c46c969b938
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
