name: "Python CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@307c66955ab6d811fbeb45f8e49dfe5d51e5d285

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@307c66955ab6d811fbeb45f8e49dfe5d51e5d285

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11", "3.12.0-beta.3" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@307c66955ab6d811fbeb45f8e49dfe5d51e5d285
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
